# -*- coding: utf-8 -*-
"""task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NvaerZYDFD7n-o5zfxJ2OJtpVYLk8WRd
"""

import math
import os
import random
import re
import sys


if __name__ == '__main__':
     n = int(input())
     if (n%2==0) and (n in range(2,6) or n > 20):
       print('Not Weird')
     else:
       print('Weird')