# -*- coding: utf-8 -*-
"""task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15D8tYIo3mwkXoLI3Rxg9EBLuuneiK7v3
"""

if __name__ == '__main__':
    a = int(input())
    b = int(input())
    print(a//b)
    print(a/b)