# -*- coding: utf-8 -*-
"""task7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Tf7sXHE57OQ2HX6FTcInOowoS-QJsOp
"""

if __name__ == '__main__':
    n = int(input())
    for i in range(1,n+1):
        print(i,end="")