# -*- coding: utf-8 -*-
"""task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYRDOXZ6CvLtWaTZ7P45AwKN33CGLOSn
"""

if __name__ == '__main__':
    n = int(input())
    for i in range(0, n):
        print(i ** 2)