# -*- coding: utf-8 -*-
"""task6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JsB2oNokBbhKxIPGxXq-oavAz_ql6z4P
"""

def is_leap(year):
    leap = False
    if year % 4 == 0:
        leap = True
    
    if year % 4 == 0 and year % 100 == 0:
        leap = False

    if year % 4 == 0 and year % 100 == 0 and year % 400 == 0:
        leap = True
    
    return leap

year = int(input())
print(is_leap(year))