# -*- coding: utf-8 -*-
"""Task_4Str4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Za4go-zOFyy5nhMypmuZ46WqOgQVL1kF
"""

def mutate_string(string, position, character):
    lis = list(string)
    lis[position] = character
    return ''.join(lis)

if __name__ == '__main__':
    s = input()
    i, c = input().split()
    s_new = mutate_string(s, int(i), c)
    print(s_new)