# -*- coding: utf-8 -*-
"""Task_4Str3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b3yOXZzSOyeO5eDwk_2xGWBxCgrWouAE
"""

def print_full_name(first, last):
    # Write your code here
    print("Hello %s %s! You just delved into python."%(first,last))

if __name__ == '__main__':
    first_name = input()
    last_name = input()
    print_full_name(first_name, last_name)