# -*- coding: utf-8 -*-
"""Task_4Str2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hysV0xJfZpdkLim8qQz0bpPOUCPiSW6N
"""

def split_and_join(line):
    a = line.split(" ")
    a = "-".join(a)
    return a
    # write your code here

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)