# -*- coding: utf-8 -*-
"""Task_3Adv4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqtlWIXLP8WqmZhREDHctMuXvNwDOF-g
"""

class Solution:
    def numberOfSteps(self, num: int) -> int:
        ans = 0
        while num > 0:
            if num % 2: num -= 1
            else: num /= 2
            ans += 1
        return ans