# -*- coding: utf-8 -*-
"""Task_3Adv1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VhJjKRLiX2-VOVtFnKEK99WuELx8DeZ9
"""

class Solution:
    def maxProduct(self, nums: List[int]) -> int:
        nums = sorted(nums)
        return (nums[-1]-1)*(nums[-2]-1)