# -*- coding: utf-8 -*-
"""Task_3Adv5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PcCaVFtTmfYtI3fe_7gD8PhXBkCEjKmn
"""

class Solution:
    def countBits(self, n: int) -> List[int]:
        dp = [0]
        for i in range(1, n+1):
            bits_count = dp[i // 2]
            if i & 1:
                bits_count += 1
            dp.append(bits_count)
        return dp