# -*- coding: utf-8 -*-
"""Task_4Adv2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2Sshyc1DpItdpdF4zNP_JOMIybeGhtT
"""

class Solution:
    def sortByBits(self, arr: List[int]) -> List[int]:
        return sorted(arr, key = lambda x: (bin(x).count('1'), x))