# -*- coding: utf-8 -*-
"""Task_4Adv3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jzzmYvkAWfWp5GtToiPoGEItB1orSZJ5
"""

class Solution:
    def singleNumber(self, nums: List[int]) -> List[int]:
        emptylist=[]
        for i in nums:
            if nums.count(i)==1:
                emptylist.append(i)
        return emptylist

