# -*- coding: utf-8 -*-
"""task_2adv4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117A0_pxGjn32FZxxApITylNNqEKQMl3W
"""

class Solution:
    def smallerNumbersThanCurrent(self, nums: List[int]) -> List[int]:
        return [sum(1 for i in nums if i < j) for j in nums]