# -*- coding: utf-8 -*-
"""task_2adv3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AKyDdNOG27MNuv4gGXOucNAfzufEuHKb
"""

class Solution:
    def findNumbers(self, nums: List[int]) -> int:
        count=0
        for num in nums:
            if len(str(num)) % 2 == 0:
                count+=1

        return count