# -*- coding: utf-8 -*-
"""task_2adv5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I4qfIRPyqB3hvLFtWYA89zCT9Xg7aiJd
"""

class Solution:
    def subtractProductAndSum(self, n: int) -> int:
        product = 1
        sum_total = 0
        for i in str(n):
            product*=int(i)
            sum_total+=int(i)
        return product - sum_total