# -*- coding: utf-8 -*-
"""task_3Math3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-O7y9CsMFpD3q34ebxvYcTys8Ge0H-Uo
"""

for i in range(1,int(input())+1): #More than 2 lines will result in 0 score. Do not leave a blank line also
    print((10**i//9)**2)