# -*- coding: utf-8 -*-
"""task_3Math5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LEeZ_iiHWSljQUSQsL9ZsqoIFZfgb_4x
"""

a=int(input())
b=int(input())
m=int(input())

print(pow(a,b))
print(pow(a,b,m))