# -*- coding: utf-8 -*-
"""task_3Math4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Tz8g1sJyWWnHevJr_IorDnERlIDwaEV
"""

A = int(input())
B = int(input())
print(A//B)
print(A%B)
print(divmod(A, B))