# -*- coding: utf-8 -*-
"""task_3Math6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tGSF9VUu6XOSy97xqe96eGCP8H0pENCQ
"""

a = int(input())
b = int(input())
c = int(input())
d = int(input())
print((a**b)+(c**d))