# -*- coding: utf-8 -*-
"""task_3Math1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15LflrGdrrQPf2igS2-ko3H5KoeqWIUHH
"""

from cmath import sqrt,phase
c = complex(input())

print(sqrt(pow(c.real,2)+pow(c.imag,2)).real)
print(phase(complex(c.real,c.imag)))