# -*- coding: utf-8 -*-
"""task_2_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQ0QAc3U7j1ZHtyTixIxDoB3jp1nrNZL
"""

if __name__ == '__main__':
    n = int(input())
    
    arr = list(map(int, input().split()))
    arr.sort(reverse=True)
   
    for i in range(len(arr)):
        if arr[i]!=arr[i+1]:
            break
        else:
            continue
    print(arr[i+1])