# -*- coding: utf-8 -*-
"""task_2_tup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BpqcpRUAWpGp0RzURLanfick1GOx6zff
"""

if __name__ == '__main__':
    n = int(raw_input())
    integer_list = map(int, raw_input().split())
    int_tuple = tuple(integer_list)
    print(hash(int_tuple))